client.println("<!DOCTYPE html>");
client.println("<html lang=\"de\">");
client.println("<head>");
client.println("<meta charset=\"UTF-8\">");
client.println("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
client.println("<title>Zugangskontrollsystem</title>");
client.println("<style>");
client.println("body {");
client.println("font-family: Arial, sans-serif;");
client.println("margin: 20px;");
client.println("background-color: #f0f0f0;");
client.println("}");
client.println(".container {");
client.println("max-width: 800px;");
client.println("margin: auto;");
client.println("background-color: #fff;");
client.println("padding: 20px;");
client.println("border-radius: 8px;");
client.println("box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);");
client.println("}");
client.println("header {");
client.println("text-align: center;");
client.println("margin-bottom: 20px;");
client.println("}");
client.println("header h1 {");
client.println("color: #007bff;");
client.println("margin: 0;");
client.println("font-size: 2em;");
client.println("}");
client.println("section {");
client.println("margin-bottom: 20px;");
client.println("}");
client.println("section h2 {");
client.println("color: #007bff;");
client.println("margin-top: 0;");
client.println("font-size: 1.5em;");
client.println("}");
client.println(".input-container {");
client.println("display: flex;");
client.println("align-items: center;");
client.println("margin-bottom: 10px;");
client.println("}");
client.println(".input-container input {");
client.println("padding: 10px;");
client.println("margin-right: 10px;");
client.println("flex: 1;");
client.println("border: 1px solid #ccc;");
client.println("border-radius: 4px;");
client.println("font-size: 1em;");
client.println("}");
client.println(".input-container button {");
client.println("padding: 10px 20px;");
client.println("background-color: #007bff;");
client.println("color: white;");
client.println("border: none;");
client.println("border-radius: 4px;");
client.println("cursor: pointer;");
client.println("font-size: 1em;");
client.println("}");
client.println(".btn-remove {");
client.println("background-color: #dc3545;");
client.println("padding: 10px 20px;");
client.println("color: white;");
client.println("border: none;");
client.println("border-radius: 4px;");
client.println("cursor: pointer;");
client.println("font-size: 1em;");
client.println("}");
client.println(".log, .keys {");
client.println("border: 1px solid #ccc;");
client.println("padding: 10px;");
client.println("border-radius: 4px;");
client.println("max-height: 200px;");
client.println("overflow-y: auto;");
client.println("background-color: #f8f9fa;");
client.println("}");
client.println(".log {");
client.println("margin-top: 10px;");
client.println("min-height: 80px;");
client.println("}");
client.println(".keys {");
client.println("min-height: 40px;");
client.println("margin-top: 10px;");
client.println("}");
client.println(".log div, .keys div {");
client.println("margin-bottom: 5px;");
client.println("padding: 5px 10px;");
client.println("background-color: #fff;");
client.println("border-radius: 4px;");
client.println("word-wrap: break-word;");
client.println("}");
client.println("</style>");
client.println("</head>");
client.println("<body>");
client.println("<header>");
client.println("<h1>Zugangskontrollsystem</h1>");
client.println("</header>");
client.println("<div class=\"container\">");
client.println("<section>");
client.println("<h2>Neuen Schlüssel hinzufügen</h2>");
client.println("<div class=\"input-container\">");
client.println("<input type=\"text\" id=\"nameInput\" placeholder=\"Name eingeben\">");
client.println("<button onclick=\"addName()\">Hinzufügen</button>");
client.println("</div>");
client.println("</section>");
client.println("<section>");
client.println("<h2>Schlüsselverwaltung</h2>");
client.println("<button onclick=\"toggleRemoveMode()\" class=\"btn-remove\">Entfernmodus</button>");
client.println("<section>");
client.println("<h3>Protokoll</h3>");
client.println("<div class=\"log\" id=\"log\">");
client.println("<!-- Hier wird das Protokoll angezeigt -->");
client.println("</div>");
client.println("</section>");
client.println("<section>");
client.println("<h3>Verfügbare Schlüssel</h3>");
client.println("<div class=\"keys\" id=\"keys\">");
client.println("<!-- Hier werden die verfügbaren Schlüssel angezeigt -->");
client.println("</div>");
client.println("</section>");
client.println("</section>");
client.println("</div>");
client.println("<script>");
client.println("function addName() {");
client.println("let nameInput = document.getElementById('nameInput').value.trim();");
client.println("if (nameInput !== '') {");
client.println("fetch('http://' + window.location.hostname + ':80/add?key=' + nameInput)");
client.println(".then(response => response.json());");
client.println("}");
client.println("}");
client.println("function toggleRemoveMode() {");
client.println("fetch('http://' + window.location.hostname + ':80/removeMode')");
client.println(".then(response => response.json());");
client.println("}");
client.println("</script>");
client.println("</body>");
client.println("</html>");
